console.log("2nd line added")
console.log("th line added")
console.log("2nd line added")
console.log("3rd line added")
console.log('Testing merge')
console.log("2nd line added")
console.log("7th line added")
console.log('Testing merge')
console.log('Testing merge')
